services:
  backend:
    build: ./backend
    container_name: insurance-rag-api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/chroma_store:/code/chroma_store

  frontend:
    build: ./frontend
    container_name: insurance-rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend